#!/bin/bash

# echo "Adding some modules"
# module add the_module_you_need_but_dont_deserve

echo "#################"
echo "    COMPILING    "
echo "#################"
# g++ -Wall -std=c++17 -O3 src/main.cpp src/file2 -o network

rm CMakeCache.txt
cmake .
make

echo "#################"
echo "     RUNNING     "
echo "#################"
./main


