#!/bin/bash

echo "Adding some modules"
module add gcc-10.2 llvm-11.0.0

echo "#################"
echo "    COMPILING    "
echo "#################"
# g++ -std=c++17 -O3 src/main.cpp include/main.hpp include/lingebra.hpp include/neural_network.hpp include/activation_fns.hpp include/layer.hpp include/input_loading.hpp main

rm CMakeCache.txt
cmake .
make

echo "#################"
echo "     RUNNING     "
echo "#################"
./main


